"""
Property image labels by property type.
Agent selects from these labels when uploading images.
The "front" label is used for market overview display.
"""

IMAGE_LABELS = {
    "APARTMENT": [
        "front",
        "living_room",
        "kitchen",
        "bathroom",
        "bedroom_1",
        "bedroom_2",
        "toilet",
        "balcony",
        "parking",
        "building_entrance",
    ],
    "HOUSE": [
        "front",
        "back",
        "living_room",
        "kitchen",
        "master_bedroom",
        "other_rooms",
        "bathroom",
        "toilet",
        "garden",
        "garage",
        "compound",
    ],
    "ROOM": [
        "front",
        "room_interior",
        "toilet",
        "kitchen",
        "building_entrance",
        "compound",
    ],
    "DUPLEX": [
        "front",
        "back",
        "living_room",
        "kitchen",
        "upstairs",
        "downstairs",
        "master_bedroom",
        "other_rooms",
        "bathroom",
        "toilet",
        "garden",
        "garage",
    ],
    "STUDIO": [
        "front",
        "main_room",
        "kitchen_area",
        "toilet",
        "building_entrance",
    ],
    "MANSION": [
        "front",
        "back",
        "living_room",
        "kitchen",
        "master_bedroom",
        "other_rooms",
        "bathroom",
        "toilet",
        "garden",
        "garage",
        "pool",
        "compound",
        "gate",
    ],
    "LAND": [
        "front",
        "overview",
        "boundaries",
        "access_road",
        "nearby_landmarks",
    ],
    "OFFICE": [
        "front",
        "reception",
        "work_area",
        "meeting_room",
        "kitchen",
        "toilet",
        "building_entrance",
        "parking",
    ],
    "SHOP": [
        "front",
        "interior",
        "storage",
        "toilet",
        "building_entrance",
    ],
    "WAREHOUSE": [
        "front",
        "interior",
        "loading_area",
        "office",
        "toilet",
        "compound",
    ],
}

LABEL_DISPLAY_NAMES = {
    "front": "Front View",
    "back": "Back View",
    "living_room": "Living Room",
    "kitchen": "Kitchen",
    "bathroom": "Bathroom",
    "bedroom_1": "Bedroom 1",
    "bedroom_2": "Bedroom 2",
    "master_bedroom": "Master Bedroom",
    "other_rooms": "Other Rooms",
    "toilet": "Toilet",
    "balcony": "Balcony",
    "parking": "Parking",
    "building_entrance": "Building Entrance",
    "garden": "Garden",
    "garage": "Garage",
    "compound": "Compound",
    "upstairs": "Upstairs",
    "downstairs": "Downstairs",
    "room_interior": "Room Interior",
    "main_room": "Main Room",
    "kitchen_area": "Kitchen Area",
    "overview": "Overview",
    "boundaries": "Boundaries",
    "access_road": "Access Road",
    "nearby_landmarks": "Nearby Landmarks",
    "reception": "Reception",
    "work_area": "Work Area",
    "meeting_room": "Meeting Room",
    "interior": "Interior",
    "storage": "Storage",
    "loading_area": "Loading Area",
    "office": "Office",
    "pool": "Swimming Pool",
    "gate": "Gate",
}


def get_labels_for_property_type(property_type_name: str) -> list:
    return IMAGE_LABELS.get(property_type_name.upper(), [])


def get_label_display_name(label: str) -> str:
    return LABEL_DISPLAY_NAMES.get(label, label.replace("_", " ").title())
